config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :complaint_lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "complaint_lists#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complaint_list.rb
class ComplaintList < ApplicationRecord
    before_save :default_values

    private
    def default_values
        self.status ||= "Pending"
    end

    belongs_to :user
    validates_presence_of :user
    validates :title, :presence => true
    resourcify
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :todo_lists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:user_name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:user_name, :email, :password, :current_password) }
  end
end

app/controllers/complaint_lists_controller.rb
class ComplaintListsController < ApplicationController
  before_action :set_complaint_list, only: [:show, :edit, :update, :destroy, :complete]
  before_action :authenticate_user!

  # GET /complaint_lists
  # GET /complaint_lists.json
  def index
    if !current_user.has_role?(:admin)
      @complaint_lists = ComplaintList.where(:user_id => current_user.id)
    else
      @complaint_lists = ComplaintList.all
    end
  end

  # GET /complaint_lists/1
  # GET /complaint_lists/1.json
  def show
  end

  # GET /complaint_lists/new
  def new
    @complaint_list = ComplaintList.new
  end

  # GET /complaint_lists/1/edit
  def edit
  end

  # POST /complaint_lists
  # POST /complaint_lists.json
  def create
    @complaint_list = ComplaintList.new(complaint_list_params)
    @complaint_list.user_id = current_user.id

    respond_to do |format|
      if @complaint_list.save
        format.html { redirect_to @complaint_list, notice: 'Complaint list was successfully created.' }
        format.json { render :show, status: :created, location: @complaint_list }
      else
        format.html { render :new }
        format.json { render json: @complaint_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaint_lists/1
  # PATCH/PUT /complaint_lists/1.json
  def update
    respond_to do |format|
      if @complaint_list.update(complaint_list_params)
        format.html { redirect_to @complaint_list, notice: 'Complaint list was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint_list }
      else
        format.html { render :edit }
        format.json { render json: complaint_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaint_lists/1
  # DELETE /complaint_lists/1.json
  def destroy
    @complaint_list.destroy
    respond_to do |format|
      format.html { redirect_to complaint_lists_url, notice: 'Complaint list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_complaint_list
    @complaint_list = ComplaintList.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def complaint_list_params
    params.require(:complaint_list).permit(:title, :description, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def has_role?(role)
    current_user && current_user.has_role?(role)
  end
end

app/helpers/complaint_lists_helper.rb
module ComplaintListsHelper
end

app/views/complaint_lists/_form.html.erb
<%= form_with(model: complaint_list, local: true) do |form| %>
  <% if complaint_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint_list.errors.count, "error") %> prohibited this complaint_list from being saved:</h2>

      <ul>
      <% complaint_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if !has_role?(:admin) %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

  <% else %>
    <div class="field">
      <%= form.label :status %>
      <%= form.select :status, options_for_select([['Pending'],['Processing'],['Completed']]) %>
    </div>

  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/complaint_lists/edit.html.erb
<h1>Editing Complaint List</h1>

<%= render 'form', complaint_list: @complaint_list %>

<%= link_to 'Show', @complaint_list %> |
<%= link_to 'Back', complaint_lists_path %>

app/views/complaint_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complaint Lists</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <% if has_role?(:admin) %>
        <td>User</td>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaint_lists.each do |complaint_list| %>
      <tr>
        <td><%= complaint_list.title %></td>
        <td><%= complaint_list.description %></td>
        <td><%= complaint_list.status %></td>
        <% if has_role?(:admin) %>
          <td><%= (User.find(complaint_list.user_id)).user_name rescue ActiveRecord::RecordNotFound%></td>
        <% end %>
        <td><%= link_to 'Show', complaint_list %></td>
        <td><%= link_to 'Edit', edit_complaint_list_path(complaint_list) %></td>
        <% if !has_role?(:admin) %>
          <td><%= link_to 'Close', complaint_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if !current_user.has_role?(:admin) %>
  <%= link_to 'New Complaint List', new_complaint_list_path %>
<% end %>


<%# else %>
<!--  <h1>Users</h1>-->
<!--  <table>-->
<!--    <thead>-->
<!--    <tr>-->
<!--      <th>id</th>-->
<!--      <th>Username</th>-->
<!--      <th>Processing Complaints</th>-->
<!--      <th>Pending Complaints</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--    </thead>-->

<!--    <tbody>-->
    <%# @users.each do |user| %>
<!--      <tr>-->
<!--        <td><%#= user.id %></td>-->
<!--        <td><%#= link_to user.email.split('@')[0] %></td>-->
<!--        <td><%#= link_to 'Show', complaint_list %></td>-->
<!--        <td><%#= link_to 'Edit', edit_complaint_list_path(complaint_list) %></td>-->
<!--        <td><%#= link_to 'Destroy', complaint_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <%# end %>
<!--    </tbody>-->
<!--  </table>-->

<!--  <br>-->

app/views/complaint_lists/new.html.erb
<h1>New Complaint List</h1>

<%= render 'form', complaint_list: @complaint_list %>

<%= link_to 'Back', complaint_lists_path %>

app/views/complaint_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @complaint_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @complaint_list.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @complaint_list.status %>
</p>

<%= link_to 'Edit', edit_complaint_list_path(@complaint_list) %> |
<%= link_to 'Back', complaint_lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>COMPLAINT MANAGEMENT APP</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "complaint management app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path , class: "btn "%></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path, class: "btn "  %></li>
          <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "btn " %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "btn " %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>
</body>
</html>